apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    app: app
spec:
  containers:
    - name: app-container
      image: busybox
      command: ['sh', '-c', 'echo The app is running! && sleep 1']
  restartPolicy: Never
